[package]
name = "neira"
version = "0.1.0"
edition = "2021"

[dependencies]
backend = { path = "backend" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
[package.metadata]
rustflags = ["-Dwarnings"]

[dev-dependencies]
assert_cmd = "2"
