[package]
name = "neira"
version = "0.1.0"
edition = "2021"

[dependencies]
backend = { path = "backend" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
 jsonschema-valid = "0.5.2"
once_cell = "1"

[dev-dependencies]
serde_yaml = "0.9"
tempfile = "3"
[package.metadata]
rustflags = ["-Dwarnings"]

[patch.crates-io]
kqueue-sys = { path = "patches/kqueue-sys" }
