name: CI

# neira:meta
# id: NEI-20250101-000006-ci-validate-examples
# intent: ci
# summary: Validate example organs and ensure node ID docs are up to date.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Validate Cargo files
        run: cargo metadata --locked
      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix frontend
      - name: Check duplicate crates
        run: scripts/check-duplicates.sh
      - name: Lint
        run: npm run lint
      - name: Validate examples
        run: npm run check-examples
      - name: Verify node ID docs
        run: |
          npm run generate-node-docs
          git diff --exit-code docs/node-ids.md
      - name: Test backend
        run: cargo test --manifest-path backend/Cargo.toml
      - name: Test frontend
        run: npm test --prefix frontend
      - name: Test root
        run: npm test
