name: CI

# neira:meta
# id: NEI-20250101-000006-ci-validate-examples
# intent: ci
# summary: Validate example organs and ensure cell ID docs are up to date.

# neira:meta
# id: NEI-20250310-cell-templates-ci-env
# intent: ci
# summary: Установлена переменная CELL_TEMPLATES_DIR для тестов.

# neira:meta
# id: NEI-20260422-ci-rename-components
# intent: ci
# summary: Обновлены пути на spinal_cord и sensory_organs.

# neira:meta
# id: NEI-20260610-ci-github-output
# intent: ci
# summary: Обновлены actions для вывода через $GITHUB_OUTPUT.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CELL_TEMPLATES_DIR: ./templates
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@stable
      - name: Validate Cargo files
        run: cargo metadata --locked
      - name: Install dependencies
        run: |
          npm ci
          npm ci --prefix sensory_organs
      - name: Check duplicate crates
        run: scripts/check-duplicates.sh
      - name: Lint
        run: npm run lint
      - name: Validate examples
        run: npm run check-examples
      - name: Verify cell ID docs
        run: |
          npm run generate-cell-docs
          git diff --exit-code docs/cell-ids.md
      - name: Test spinal cord
        run: cargo test --manifest-path spinal_cord/Cargo.toml
      - name: Test sensory organs
        run: npm test --prefix sensory_organs
      - name: Test root
        run: npm test
