name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75
          override: true
          components: clippy
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run JS tests
        run: npm test
      - name: Run Rust tests
        run: cargo test
      - name: Run Clippy
        run: cargo clippy -- -D warnings
